---
title: Altair Cliff Associates LLC
timezone: UTC
destination: ./docs

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Investment Philosophy Embrace Uncertainty – We think about investing
  as making moves into the right side of the chart, because every moment is unique
  and anything can happen on the right side of th…
baseurl: 
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-archives
sass:
  sass_dir: _sass
  style: compressed

jekyll-archives:
  enabled:
    - categories
    - month
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'